leanprover/verso

src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Doc/Elab/Monad.lean

Otherwise, sections that use block extensions and that have more than 64 blocks in them could sometimes fail elaboration, because Lean would infer a type with a metavariable for the intermediate let binding introduced by the elaborator.

fix: add type annotations to blocks

---

examples/website/DemoSite/Blog/Conditionals.lean
examples/website/static_files/style.css
src/verso-blog/Verso/Genre/Blog/Basic.lean
src/verso-blog/Verso/Genre/Blog/HighlightCode.lean
src/verso-blog/Verso/Genre/Blog/Highlighted.lean
src/verso-blog/Verso/Genre/Blog/Template.lean

This is a bit limited because Lean isn't tagging all the expressions, e.g. names in application positions (the same problems are visible in the infoview), but this can be improved upstream.

feat: highlighting and popups in tactic states

---

examples/website/DemoSite/Blog/Conditionals.lean
src/verso-blog/Verso/Genre/Blog/HighlightCode.lean
src/verso-blog/Verso/Genre/Blog/Highlighted.lean
src/verso-blog/Verso/Genre/Blog/Template.lean

Now keywords don't show their parser names, and they participate in occurrence highlighting

feat: redo keyword highlighting

---

lake-manifest.json
lakefile.lean
lean-toolchain
src/verso/Verso/Doc.lean
src/verso/Verso/Doc/Html.lean
src/verso/Verso/Doc/Lsp.lean
src/verso/Verso/Examples.lean
src/verso/Verso/Method.lean
src/verso/Verso/Output/Html.lean
src/verso/Verso/Output/TeX.lean
src/verso/Verso/Parser.lean

Now that the code uses Lean nightlies anyway, and all the needed bits have been upstreamed, might as well not have the extra dependency for now.

chore: remove Std dependency

---

.gitignore

Ignore the outputs of `lake build`.

chore: ignore .lake and _out

---

src/verso-blog/Verso/Genre/Blog/Basic.lean

This prevents hover rules from unpredictably triggering on phones as users try to scroll.

fix: guard CSS hover rules in a media query

---

src/verso-blog/Verso/Genre/Blog/Template.lean
src/verso/Verso/Output/Html.lean

Fixes a problem with white-space: pre;

fix: strip leading and trailing whitespace from highlights

---

examples/website-examples/lake-manifest.json
examples/website/DemoSite/Blog/Conditionals.lean
lake-manifest.json
src/verso-blog/Verso/Genre/Blog/Basic.lean
src/verso-blog/Verso/Genre/Blog/Template.lean

This prevents horrible nests of info hovers when there's more than one on a source span.
Incorporates https://github.com/leanprover/subverso/pull/13.

fix: stack info hovers in a single window

---

examples/website-examples/Examples/Basic.lean
examples/website-examples/lake-manifest.json
examples/website/DemoSite/Blog/Subprojects.lean
lake-manifest.json

This bumps SubVerso to allow references to names that aren't elaborated as terms.

feat: support name references in subprojects

---

UsersGuideMain.lean
examples/textbook/DemoTextbook/Exts/Exercises.lean
examples/textbook/DemoTextbook/Exts/Index.lean
examples/textbook/DemoTextbookMain.lean
generate.sh
lean-toolchain
src/verso-manual/Verso/Genre/Manual.lean
src/verso-manual/Verso/Genre/Manual/Basic.lean
src/verso-manual/Verso/Genre/Manual/Docstring.lean
src/verso/Verso/Doc/Elab/Monad.lean

It's no longer necessary to manually pass a list of extension implementations to `manualMain` - they're saved in a registry and inserted automatically.

feat: automatic finding of extension descriptors in manual

---

src/verso-blog/Verso/Genre/Blog/Basic.lean
src/verso-blog/Verso/Genre/Blog/Theme.lean

I hope this PR is welcome.
To the best of my knowledge, 2024-7-17 is not a valid ISO 8601 date (I don't have access to ISO 8601 itself, the closest I could come was RFC 3339, according to which it is not a valid date). Of course I don't claim that my proposed change is anything close to a proper date formatting routine, but it should ensure that at least all of the dates on the Lean blog are valid. With Time.lean moving to core, we will hopefully have access to a good formatter in the not-too-distant future. The only reason why I'm proposing to change this beforehand is because it keeps annoying me whenever I open the Lean blog :)
Post URLs are unaffected by this change.

fix: leading zero for single-digit days and months in ISO 8601 dates

---

src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Doc/Elab.lean
src/verso/Verso/Doc/Elab/Incremental.lean
src/verso/Verso/Doc/Elab/Monad.lean

Fixes incremental reporting, which previously suffered from two problems:
1. Snapshot message logs were restored only when states were to be re-used, but message logs capture the log at the _start_ of the elaboration step and thus should be unconditionally restored. This led to the step immediately prior to buffer damage losing its messages.
2. It was inconvenient to disable incrementality for "finishing" commands, so it didn't happen in practice. Now, the finishing command is provided as a parameter to incrementallyElabCommand, so the framework can arrange for it to be run correctly and the details of promises that need resolving are not exposed. This led to the final messages getting lost, while now they're saved. Footgun removal!

fix: incremental message logs - off-by-one fix and footgun removal

---

Main.lean
examples/custom-genre/SimplePage.lean
src/verso-blog/VersoBlog.lean
src/verso-blog/VersoBlog/Generate.lean
src/verso-blog/VersoBlog/Template.lean
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Glossary.lean
src/verso-manual/VersoManual/Index.lean
src/verso/Verso/Code/Highlighted.lean
src/verso/Verso/Doc/Html.lean

Adds the ability to provide a link target specifier to HTML code rendering, as well as support for code/docs cross-references in the manual genre.

feat: cross-references from code

---

examples/website-examples/lake-manifest.json
lake-manifest.json
src/verso/Verso/Code/Highlighted.lean

Adds cross-reference support for option names (and a few other tokens), and updates to the version of SubVerso that correctly generates them.

feat: Tooltips and xrefs for options

---

src/verso/Verso/Doc/Elab/Monad.lean

This allows TermElabM actions and tactics to create auxiliary definitions.

fix: set a declaration name

---

src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Glossary.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Index.lean
src/verso-manual/VersoManual/Slug.lean
src/verso-manual/VersoManual/WebAssets.lean
static-web/find.js

This is JS that transforms entries in the Verso xref table into actual links or redirects. This will be suitable for incoming links from docstrings or Zulip.

feat: automatic linkifier

---

src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Draft.lean

Building a manual can now be done in draft mode, which can cause draft-conditional content to appear (this can be useful for e.g. reviews of PRs)

feat: --draft flag

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html.lean
src/verso/Verso/Code/Highlighted.lean

Before, hovers only worked when the site was hosted at the root, because the link-relativization pass doesn't reach into JS string literals. This simple fix seems to take care of it.

Allow manual genre to be hosted not at the root

---

.github/workflows/ci.yml

Try to avoid getting only the first cache for each Lean version. That's nice, but more recent pushes are more likely to be similar to what I'm pushing now.

chore: more specific cache keys for CI

---

src/verso-manual/VersoManual/Index.lean

The prior CSS led to overlapping columns and unreadable text.

fix: non-overlapping rendering of index

---

src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Glossary.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Index.lean

This is required for relative URLs to work as they should, and not all hosts add them.

fix: include trailing slashes in links

---

src/verso-manual/VersoManual/Html/Style.lean

In the manual genre, the hide/show animation for the ToC didn't actually resize the element, making it useless for getting more content space on small screens.

fix: the ToC hide/show animation didn't resize body

---

doc/UsersGuide/Markup.lean
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean
static-web/find.js

Now objects in the HTML output from the manual genre can opt in to permalink widgets.
Fixes #200, for more than just section names, though it will only create links to sections with assigned stable names. Next step: assign them over in leanprover/reference-manual :)

feat: permalink widgets

---

src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Html.lean

Sets all URLs to be relative to a given base. Setting this to the hosting root, then making all intra-site URLs relative to that, should fix trailing slash issues.

feat: optional base tag

---

Main.lean
examples/custom-genre/SimplePage.lean
examples/website-examples/lake-manifest.json
examples/website/DemoSite/Blog/Conditionals.lean
lake-manifest.json
src/verso-blog/VersoBlog/Generate.lean
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso/Verso/Code/Highlighted.lean
src/verso/Verso/Doc/Html.lean

Code samples can now detect defined names and generate links to them, just as there were previously links to docstrings from code samples. This will help make the Markdown docstrings render usefully in the manual genre.

feat: working example definition link targets

---

src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean
src/verso-manual/VersoManual/Index.lean
src/verso/Verso/Code/Highlighted.lean

* Switch to rems universally
* Include the magic "I know what I'm doing" meta tag
Based on advice in https://github.com/leanprover/reference-manual/issues/140 and https://github.com/leanprover/reference-manual/issues/137. It won't solve all the issues, and it requires a bit more testing, but a quick check was positive.

fix: use better mobile CSS for highlighted code and in manuals

---

src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Parser.lean
src/verso/Verso/Parser/Lean.lean
src/verso/Verso/SyntaxUtils.lean

Now errors are shown on the directives in the source file, rather than at the end of the file, making it much easier to diagnose parser errors.

fix: error recovery for directives

---

src/verso/Verso/Parser.lean
src/verso/Verso/Syntax.lean

This uses the CommonMark convention that if inline code begins and ends with spaces, the first and last are stripped.
Also enables newlines in code/math inlines.

feat: allow code inlines to contain leading/trailing `

---

src/verso-manual/VersoManual/Html.lean

This can work around issues with web hosts that don't allow slash behavior to be configured, at least for some clients.

fix: add JS to add trailing slashes

---

.github/workflows/ci.yml
.github/workflows/consistent-subverso-manifests.yml

Moving the Subverso consistency check to its own job improves parallel processing and fails faster.
Also, there's no need to run on push and on pull request - it'd be nice to kick off builds when the push happens, but this results in double builds, which is not good.

chore: improve CI parallelism

---

src/verso-manual/VersoManual/Docstring.lean

* Sort namespaces alphabetically
* Valid code for docstring generation

feat: small quality of life improvements in progress tracker

---

src/verso-manual/VersoManual/Index.lean

This reduces local builds of the reference manual from 80s to 48s for me.

perf: use a better data structure for the index

---

lean-toolchain
src/verso-manual/VersoManual/Docstring.lean
src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Doc/Elab.lean
src/verso/Verso/Doc/Elab/Monad.lean
src/verso/Verso/Doc/Lsp.lean
src/verso/Verso/Syntax.lean

This fixes compatibility with upstream changes to LSP internals. In the process, the refactoring of the syntax representation was propagated to the semantic token highlighter, greatly improving it.

chore: bump to new nightly

---

src/verso-manual/VersoManual/Glossary.lean

The prior implementation essentially treated them as a unary counter, which led to comically long and uninformative HTML IDs.

fix: non-absurd anchors on technical terms

---

doc/UsersGuide/Basic.lean
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean
src/verso-manual/VersoManual/LocalContents.lean

Adds things like docstrings to the ToC on the left in the manual genre. The set of things to be shown is extensible.
Closes #266.

feat: show summary of current page in manual genre

---

src/verso-manual/VersoManual/Docstring.lean
src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Doc/Elab/Monad.lean

This better reflects the fact that each Verso block is roughly equivalent to a Lean command. Asking the entire document to stay within heartbeat limits doesn't make so much sense.

feat: reset heartbeat count for each top-level block

---

src/verso/Verso/Doc/Elab.lean
src/verso/Verso/Parser.lean

This allows Verso metaprograms to use quasiquotes correctly.

fix: represent parsed arguments as Lean syntax expects

---

src/verso/Verso/Doc/Elab/Incremental.lean

With the advent of parallelism, the progress bar now shows the union of the child nodes' spans. This is a quick fix to have the next child be the rest of the file; once Verso gets proper parallel elaboration, this will no longer suffice.

fix: show accurate progress bar during incremental elaboration

---

src/verso-manual/VersoManual/Html/Style.lean

The intention here is to improve legibility of the reference manual and other texts that will be generated from verso.
> feat: reduce font size on desktop
> 
> Since we use `rem` almost everywhere, the effect on the whole page is
> that it is slightly zoomed out. It doesn't increase the number of
> characters per line.
> 
> 16px is taken from MDN, the rust book, and stack overflow. It is the
> most common font size on the web.
> feat: increase line-height for body content
> 
> I investigated line heights from MDN and the rust book, and picked the
> lesser one out of caution. To me, it increases legibility.

feat: improve legibility

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean
src/verso-manual/VersoManual/Index.lean

This has a bunch of ideas related to issues https://github.com/leanprover/reference-manual/issues/316 , https://github.com/leanprover/reference-manual/issues/317 , https://github.com/leanprover/reference-manual/issues/318 , and https://github.com/leanprover/reference-manual/issues/319 .
It builds on top of the sans-serif pull request, so this is the combined changes.
Items addressed:
- Add a fixed header
- Reduce font size on desktop
- Increase line height for body content
- Make margins on all sides of definition boxes the same size.
- Decrease the font size of the definition header text
- Reduce index header font size
- Make the index header not stick on mobile
- Make the index always single-column
- Disable toc hide/show on desktop
I'll add more tomorrow.

feat: several style changes for verso manuals

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Index.lean

This fixes two minor UI things. It makes the distance between index elements smaller, and removes the white box in empty definition boxes.
Before:
After:
And the definition boxes. Before:
After:

Small UI fixes

---

README.md
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean

This PR is in draft, because it needs the title of the manual currently being worked on - right now it is hardcoded to "The Lean Language Reference". Other than that, it's ready to go.
The move to the ToC is implemented such that it is easy to overwrite for
dependents. They will need to add the following css to their theme
file:
```css
/* Move the title from the header to the toc when there is not enough room. */
@media screen and (max-width: 1200px) {
.toc-title {
display: block;
}
.header-title {
display: none;
}
}
```

Put the title in the header for manuals built on Verso

---

src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean

Moves next/previous buttons to the content part of the page. This provides for nicer ergonomics, because it feels more like turning pages in a book, and you can also see what the next chapter is directly.
Closes https://github.com/leanprover/reference-manual/issues/322.

feat: prev-next links on the pages

---

README.md
src/verso-manual/VersoManual/Html/Style.lean

These changes make it so that the title doesn't move from the header bar to the table of contents by default. This means that some books will have an overflowing header on small devices by default, but it will be easy to notice and it is easy to fix.
The header bar needs to always be displayed, because that's where the menu button lives. For books with long titles and no logo, who set the boundary higher than 700px, this will cause the header bar to be empty from 700px to the set width. I don't expect this to be a problem until we move the quick jump from the reference manual to Verso, but then the header bar also won't be empty anymore.

fix: don't hide the header bar

---

src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/Html/Style.lean

This fixes two issues:
- The first and last pages of the book, the next/previous button would take up the full width, which was too much.
- On mobile, when flipping through the pages, sometimes the "next" button would move to below the "previous" button, which meant that I accidentally went back a page instead of forwards. Now, their location is consistent.
The drawback is that there will now, on mobile, be more pages where the next/prev buttons span multiple lines. But I think the tradeoff is worth it.

fix: prev-next buttons always take up exactly half the screen

---

src/verso-manual/VersoManual/Docstring.lean

fix: code block was overflowing

---

src/verso-manual/VersoManual/Html/Style.lean

The content padding doesn't need to be as large on mobile as it has to on desktop, which gives us more valuable space for content.

fix: reduce the content padding on mobile

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Docstring/Config.lean

This makes it much easier to track progress to a fully-documented manual without empty boxes.

feat: finer-grained control over missing docstring errors/warnings

---

lean-toolchain
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Html.lean
src/verso/Verso/Code/Highlighted.lean

This should fix problems with deployment other than to server roots requiring the path to be hard-coded (so we can use the same HTML for e.g. /docs/4.18.0/ and /docs/latest/).

feat: always use a relative <base> tag

---

src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Index.lean
src/verso-manual/VersoManual/Slug.lean
src/verso/Verso/Doc.lean

Significantly speeds up generating large manuals by not redundantly (de)serializing JSON.

perf: get rid of overhead from the index

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html/Style.lean
src/verso/Verso/Code/Highlighted.lean

fix: display the label consistently over namedocs headers
fix: overflowing code examples, LawfulMonad
I think this is only displayed in a few places, one of them being
`LawfulMonad.{u, v}`. Would it be possible to apply some formatting to
those examples too, so the scrolling becomes unnecessary?
fix: darker warning color (and centralize it)
I picked #E7A71D, as it has 2.11 contrast to white, which should be OK
for visual cues. The previous color was #efd871, which only has 1.42.
See https://webaim.org/resources/contrastchecker/?fcolor=EFD871&bcolor=FFFFFF.

fix: several small UI fixes

---

doc/UsersGuide/Basic.lean
src/verso-manual/VersoManual/Docstring.lean

Adds the following:
* Suppression of structure constructors
* Custom labels
Bugfix:
* When there's no fields, the header was shown. It's now shown only when there are fields.

feat: structure docstring control

---

src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Docstring/Progress.lean
src/verso-manual/VersoManual/LocalContents.lean

Closes https://github.com/leanprover/reference-manual/issues/384.
Also improves the robustness so that future errors are visible rather than swallowed.

fix: missing local items

---

examples/website-examples/lake-manifest.json
lake-manifest.json
lakefile.lean
lean-toolchain

This temporarily disables precompiled modules, which slows down elaboration of big documents. Changes from lean4#7716 made compilation not work with it enabled.

chore: bump to 2025-03-30

---

examples/website-examples/lake-manifest.json
examples/website-literate/lake-manifest.json
lake-manifest.json
src/verso-blog/VersoBlog/LiterateLeanPage.lean
src/verso/Verso/Doc/Elab/Monad.lean

The underlying process isn't safe to use this way.

fix: don't asynchronously elaborate literate files

---

src/verso-blog/VersoBlog.lean
src/verso-blog/VersoBlog/Template.lean

This is needed when they come from sources other than modules

fix: allow page names to be ordinary references as well as docnames

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html/Style.lean

Draft because the empty labels should be hidden. I couldn't figure out how to accomplish that in 5 minutes.

feat: another design for definition boxes

---

generate.sh
src/verso-manual/VersoManual.lean

The HTML splitting depth now defaults to 2, and single-page and TeX output need to be explicitly enabled.
Closes #350

fix: better defaults for manualMain

---

doc/UsersGuide/Basic.lean
src/verso-manual/VersoManual.lean
src/verso-manual/VersoManual/Basic.lean
src/verso-manual/VersoManual/Html.lean
src/verso-manual/VersoManual/LocalContents.lean
src/verso/Verso/Output/Html.lean

These short titles are used in the following circumstances where space may be constrained:
1. Left-side table of contents (main body ToCs use the full title)
2. For the root part, the short title is shown on page headers instead of the full title. The full title is still shown on the title page.
Closes #363

feat: allow parts in manuals to specify short titles

---

doc/UsersGuide/Basic.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Html/Style.lean

In the manual genre, renders signatures with multiple widths, so that media queries can select an appropriate one. This allows the design to be more responsive and waste less space.

feat: multiple signature widths

---

src/verso-manual/VersoManual/Html/Style.lean

This makes the text take up more horizontal space on big displays and keeps the book title from overlapping the menu on mobile layouts.

chore: CSS width issues

---

README.md

I'm not sure if I did something wrong, but when I ran the previous command, I only got a `http-multi` sub-directory, I didn't get `http-single`.

README: fix HTML directory for http.server

---

src/verso-blog/VersoBlog/LiterateLeanPage.lean
src/verso-manual/VersoManual/InlineLean.lean
src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Doc/Concrete/InlineString.lean
src/verso/Verso/Doc/Elab.lean
src/verso/Verso/Doc/Elab/Monad.lean
src/verso/Verso/Examples.lean
src/verso/Verso/Parser.lean

Replaces the Lean command parser with a new one that takes a block at a time, rather than parsing Verso as one giant command and implementing incrementality "by hand".

feat: alternative approach to incrementality

---

examples/documented-package/lake-manifest.json
examples/website-examples/lake-manifest.json
examples/website-literate/lake-manifest.json
lake-manifest.json
lean-toolchain
src/verso-blog/VersoBlog/LiterateLeanPage.lean
src/verso/Verso/Code/External.lean
src/verso/Verso/Code/External/Files.lean

Prevents spurious rebuilds from subprocesses and repairs broken hint formatting.

fix: external code rebuilds and hints

---

src/verso/Verso.lean
src/verso/Verso/Doc/Concrete.lean
src/verso/Verso/Hooks.lean

This allows Verso extensions to register things like cleanup functions for internal state that they can't otherwise control (e.g. temporary directories).

feat: document elaboration hooks

---

examples/package-manual/PackageManual.lean
examples/package-manual/PackageManual/DocFeatures.lean
examples/textbook/DemoTextbook.lean
src/verso/Verso/Linters.lean

In particular, this will help users not get caught on the fact that `*` is different from Markdown.

feat: add linters for extra markup

---

src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Markdown.lean
src/verso/Verso/Code/Highlighted.lean

This PR adds the Markdown elaboration features required for error explanations, namely the ability to create `Part`s from Markdown headers, the ability to access infostrings in code-block elaborators, and a "strict" inline code elaboration mode.

feat: add part generation and info-string checking in Markdown elab

---

src/verso-blog/VersoBlog/LiterateLeanPage.lean

I believe there was a typo in the docstring of `def_literate_post`.

typo: page instead of post in def_literate_post docstring

---

src/verso-blog/VersoBlog/Template.lean

The string wasn't being interpolated, so error messages were for "{x}" rather than for `x` itself.

chore: fix logError interpolation in inlineHtml

---

src/verso-manual/VersoManual/Docstring.lean
src/verso/Verso/Doc/Elab.lean

This PR hides inherited fields by default and improves the error message that occurs when block content is in a context that expects a part.

chore: improve display/ergonomics for Grind manual page

---

src/verso/Verso/Code/External.lean
src/verso/Verso/Code/External/Env.lean
src/verso/Verso/Code/External/Files.lean

This makes it more convenient to mix versions for example code.

feat: allow project selection without setting options

---

doc/UsersGuide/Extensions.lean
doc/UsersGuide/Markup.lean
doc/UsersGuide/Output.lean
examples/package-manual/PackageManual.lean
examples/package-manual/PackageManual/DocFeatures.lean
examples/textbook/DemoTextbook.lean
examples/website/DemoSite/Blog/AnchorBased.lean
examples/website/DemoSite/Blog/Conditionals.lean
examples/website/DemoSite/Blog/Subprojects.lean
src/verso-blog/VersoBlog.lean
src/verso-manual/VersoManual/Docstring.lean
src/verso-manual/VersoManual/Glossary.lean
src/verso-manual/VersoManual/InlineLean.lean
src/verso-manual/VersoManual/InlineLean/IO.lean
src/verso-manual/VersoManual/InlineLean/Signature.lean
src/verso-manual/VersoManual/InlineLean/SyntaxError.lean
src/verso-manual/VersoManual/Table.lean
src/verso/Verso/Code/External.lean
src/verso/Verso/Doc.lean
src/verso/Verso/Doc/ArgParse.lean
src/verso/Verso/Doc/Elab.lean
src/verso/Verso/Parser.lean
src/verso/Verso/Syntax.lean

Adds deprecation warnings for the old named argument syntax, and adds flag syntax similar to that of tactics.

feat: improve argument syntax

---

tag-subverso.sh

This automates the production of tags in SubVerso that correspond to tags in Verso, for multi-project setups.

feat: script for tagging SubVerso releases

---

src/verso-manual/VersoManual/InlineLean.lean

Remove newline insertion from inline name rendering. Addresses part of #513.

fix: don't insert newlines when rendering manual inline names

---

.github/workflows/ci.yml

There's a probably-not-important-for-us dependabot update on our lychee version, but the [breaking changes](https://github.com/lycheeverse/lychee-action/releases/tag/v2.0.0) for v2 all seemed to be about sensible changes to the defaults, so it doesn't seem like anything would hold us back from just updating to a v2 dependency

chore: update lychee dependency in github action

---

src/tests/Tests.lean
src/tests/Tests/ParserRegression.lean
src/verso/Verso/Parser.lean

fix: add '%%%' as a token when parsing metadata blocks

---

src/verso/Verso/Doc/Elab.lean
src/verso/Verso/Doc/Elab/Monad.lean

Modify pattern match destructuring to field projection where that's an obvious move. 
This is intended to make it less of a big diff elsewhere where I want to explore adding fields to DocElabContext. I'm also curious if stylistically there's a preferred version — I certainly would be inclined to use the (existing) pattern-destructuring notation if I had less than 3 or so fields and the fields were very stable.

refactor: pattern-match destructuring to projection for DocElabContext

---

src/verso-manual/VersoManual/Markdown.lean

Make the type `HeaderMapping` an abbreviation instead of a definition.
This change was intended as part of https://github.com/leanprover/verso/pull/539 and will make https://github.com/leanprover/reference-manual/pull/599 easier to land. There's still [one place remaining](https://github.com/leanprover/reference-manual/blob/main/Manual/Meta/ErrorExplanation.lean#L639-L640) in `Manual/Meta/ErrorExplanation.lean` which relies on the underlying implementation of `HeaderMapping`. It's convenient for now to make it an `abbrev`. Of course, we could also trivially implement `ForIn` for `HeaderMapping`, or expose a "close all sections for this `HeaderMapping` but I'd rather decouple that decision from [the present PR](https://github.com/leanprover/reference-manual/pull/599).

fix: make header mapping type abbreviation

---

.gitignore
src/tests/TestMain.lean
src/tests/Tests.lean
src/tests/Tests/Integration.lean
src/tests/Tests/Integration/SampleDoc.lean
src/tests/Tests/TexUnit.lean
src/tests/Tests/TexUtil.lean
src/tests/integration/sample-doc/expected/tex/main.tex

Add a simple integration test that runs TeX generation and compares against expected output.
Also add a couple of unit tests that directly check `toTex` on small explicitly constructed blocks.
A continuation of the attempt in #519.

chore: add tests for TeX output

---

src/verso/Verso/Code/External.lean

Anchor content suggestions were being shown on one line. This fixes that, as well as a bug where they weren't provided for indented blocks.

fix: anchor content suggestions and indentation
