leanprover/verso

- examples/website/DemoSite/Blog/Conditionals.lean
- src/verso-blog/Verso/Genre/Blog/HighlightCode.lean
- src/verso-blog/Verso/Genre/Blog/Highlighted.lean
- src/verso-blog/Verso/Genre/Blog/Template.lean
> Source code highlighting improvements

- examples/website/DemoSite/Blog/Conditionals.lean
- examples/website/static_files/style.css
- src/verso-blog/Verso/Genre/Blog/Basic.lean
- src/verso-blog/Verso/Genre/Blog/HighlightCode.lean
- src/verso-blog/Verso/Genre/Blog/Highlighted.lean
- src/verso-blog/Verso/Genre/Blog/Template.lean
Initial support for showing tactic states in HTML, a la Alectryon
Still missing:
* Diffing pre/post tactic state
* Clickable terms and hovers in tactic states
* Syntax highlighting in tactic states
> feat: show tactic states in HTML

- lake-manifest.json
- src/verso-blog/Verso/Genre/Blog.lean
- src/verso-blog/Verso/Genre/Blog/Basic.lean
- src/verso-blog/Verso/Genre/Blog/Template.lean
- src/verso/Verso/Doc.lean
- src/verso/Verso/Doc/ArgParse.lean
- src/verso/Verso/Doc/Concrete.lean
Lots of small-to-medium improvements in user-friendliness of blog-genre LSP
> Blog usability

- lake-manifest.json
This gets the included fix for choice node highlighting.
> chore: bump subverso version

- .github/workflows/ci.yml
> fix: upload all generated docs to one release/artifact

- examples/website-examples/lake-manifest.json
- lake-manifest.json
- lean-toolchain
- src/verso-blog/Verso/Genre/Blog.lean
- src/verso/Verso/Doc/ArgParse.lean
- src/verso/Verso/Doc/Concrete.lean
- src/verso/Verso/Doc/Elab.lean
- src/verso/Verso/Doc/Elab/ExpanderAttribute.lean
- src/verso/Verso/Method.lean
This paves the way for incremental elaboration, enough of which should be merged soon to get Verso working more responsively to user input.
> chore: work with newer Lean core

- examples/website-examples/lake-manifest.json
- lake-manifest.json
This makes it work with more installations of elan
> chore: bump subverso

- .github/workflows/ci.yml
- src/verso-manual/Verso/Genre/Manual.lean
- src/verso-manual/Verso/Genre/Manual/TeX.lean
- src/verso/Verso/Output/TeX.lean
This should fix #71, but this must be verified.
> chore: use memoir for LaTeX output

- examples/website-examples/lake-manifest.json
- examples/website/DemoSite/Blog/Conditionals.lean
- lake-manifest.json
- src/verso-blog/Verso/Genre/Blog.lean
- src/verso/Verso/Doc/Concrete.lean
- src/verso/Verso/Doc/Elab.lean
- src/verso/Verso/Doc/Elab/Monad.lean
This makes it easier to find performance issues that make a particular part of a document slow.
> chore: add trace nodes

- examples/website-examples/lake-manifest.json
- lake-manifest.json
- lakefile.lean
To speed up elaboration (some files by 50%)
> chore: precompile modules

- src/code-highlighting/Verso/Code/Highlighted.lean
This should eliminate flickers and multiple hovers from the new code.
> fix: flickers and competing hovers

- src/code-highlighting/Verso/Code/Highlighted.lean
Now the borders are colored rather than the background.
> fix: fix poor contrast in hovers for messages

- README.md
Add missing acknowledgment and book list
> doc: Improve README

- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/Docstring.lean
- src/verso/Verso/Doc/ArgParse.lean
- src/verso/Verso/Parser.lean
This is a number of things that became necessary while working on the reference manual.
> Manual bug fixes

- Main.lean
- examples/custom-genre/SimplePage.lean
- examples/website-examples/lake-manifest.json
- lake-manifest.json
- src/verso-blog/VersoBlog.lean
- src/verso-blog/VersoBlog/Generate.lean
- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/Docstring.lean
- src/verso/Verso/Code/Highlighted.lean
- src/verso/Verso/Doc/Html.lean
Enables proof states to be rendered alone, and in inline contexts.
> feat: more flexible proof state display

- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/Basic.lean
- src/verso-manual/VersoManual/Index.lean
- src/verso/Verso/Doc.lean
This work also exposed an edge case in the traversal state for the index, which was fixed as part of testing the new feature.
> feat: allow suppression of page-splitting for multi-page HTML output

- .github/workflows/ci.yml
This solved the slow cache upload problem in another repo
> chore: update cache CI version

- README.md
- doc/UsersGuide/Basic.lean
- examples/custom-genre/SimplePage.lean
- lakefile.lean
- src/verso-blog/VersoBlog/Basic.lean
- src/verso-blog/VersoBlog/Template.lean
- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/Basic.lean
- src/verso-manual/VersoManual/Html.lean
- src/verso-manual/VersoManual/Html/Style.lean
- src/verso/Verso/Doc.lean
- src/verso/Verso/Doc/Html.lean
This makes it much easier to navigate complicated documents, and provides an automatic breadcrumb feature.
> Manual genre: generate section numbers in HTML and use a Scribble-style left margin ToC

- src/verso-manual/VersoManual/Html.lean
- src/verso-manual/VersoManual/Html/Style.lean
> ToC usability fixes

- src/verso-manual/VersoManual/Html.lean
- src/verso-manual/VersoManual/Html/Style.lean
This helps users navigate locally.
> feat: navigation buttons in manual genre

- src/verso/Verso/Output/Html.lean
This allows attribute names like `aria-busy` and `data-foo` to be included directly in HTML templates.
> fix: adhere much more closely to the HTML spec for attribute names

- src/verso-manual/VersoManual/Docstring.lean
This parallels the block version.
> feat: add show parameter to inline tactic references

- src/verso-manual/VersoManual/Html/Style.lean
Supersedes #211 based on discussions in the thread.
> fix: double-scrolling in Chrome

- src/verso-manual/VersoManual/Html.lean
- src/verso-manual/VersoManual/Html/Style.lean
- src/verso-manual/VersoManual/Index.lean
Closes https://github.com/leanprover/reference-manual/issues/138 and https://github.com/leanprover/reference-manual/issues/155
> Further mobile phone CSS improvements for manual genre

- src/verso-manual/VersoManual/Docstring.lean
Also removes spurious constructor and projection complaints.
> fix: docstring progress tracker respects deprecation

- src/verso-manual/VersoManual/Docstring.lean
Also include example code that can be copy-pasted in the output.
> feat: improve ignore list for docstring progress tracker

- examples/website-examples/lake-manifest.json
- lake-manifest.json
This makes whole-module highlighting available to downstream clients.
> chore: bump subverso dependency

- examples/custom-genre/SimplePage.lean
- lean-toolchain
- src/verso-blog/VersoBlog.lean
- src/verso/Verso/Code/Highlighted.lean
- src/verso/Verso/Doc/Lsp.lean
Needed for temporary directories in the reference manual.
> chore: bump to new nightly

- src/verso-manual/VersoManual/Docstring.lean
- src/verso/Verso/Doc/Lsp.lean
- src/verso/Verso/Doc/PointOfInterest.lean
I kept getting lost in the manual, and these features make it easier to keep track of things (especially folding of examples).
> feat: LSP improvements

- src/verso/Verso/Doc/Lsp.lean
VS Code can't deal with certain kinds of symbols, and throws an exception. This prevents that from happening.
> feat: clean up document symbols

- .github/workflows/ci.yml
- doc/UsersGuide/Basic.lean
- lean-toolchain
- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/Docstring.lean
- src/verso-manual/VersoManual/Docstring/Config.lean
- src/verso-manual/VersoManual/Html/Style.lean
- src/verso-manual/VersoManual/Markdown.lean
- src/verso-manual/VersoManual/TeX.lean
- src/verso/Verso/Code/Highlighted.lean
- src/verso/Verso/Doc.lean
- src/verso/Verso/Doc/Elab/Monad.lean
- src/verso/Verso/Doc/TeX.lean
- src/verso/Verso/Hover.lean
- src/verso/Verso/Output/Html.lean
Adds a set of heuristics for rendering code blocks in Markdown docstrings.
> feat: heuristic Markdown docstring rendering

- lake-manifest.json
This version integrates build fixes that allow more features to work interactively.
This should fix #132
> chore: bump md4lean dependency

- src/verso-manual/VersoManual/Docstring.lean
Adds the ability to splice the contents of a docstring, as if they were written in a block location.
> feat: docstring splicing

- src/verso-manual/VersoManual/Docstring.lean
It is now also possible to locally disable it for included docstrings.
> fix: docstring heuristic rendering should skip Lake commands

- src/verso-manual/VersoManual/Html/Style.lean
This gives the right layering effects on smalls screens.
> fix: Set toc-backdrop z-index to 9, restore toc to 10

- lean-toolchain
- src/verso/Verso/Doc/Concrete.lean
- src/verso/Verso/Doc/Elab/Incremental.lean
This revealed that some promises hadn't been getting resolved, so this
change also includes an adaptation to ensure that everything not
resolved is cancelled.
> chore: bump for 2025-02-10

- src/verso-manual/VersoManual/Docstring.lean
Right now, the results need some post-processing. It'd be good to find a way to eliminate them.
> fix: use upstream pretty printer for signatures

- src/verso-manual/VersoManual/Docstring.lean
They shouldn't necessarily be shown in the manual, so don't include them in the progress tracker.
> feat: ignore simprocs in progress tracker

- src/verso-manual/VersoManual/Html/Style.lean
> feat: center main text on larger screens (> 1500 px)

- examples/website-examples/lake-manifest.json
- lake-manifest.json
- src/verso/Verso/Code/Highlighted.lean
This allows hovers to pop up for Sort, Type, and Prop.
> feat: support docstrings/hovers for sorts

- examples/website-literate/LitLean.lean
- examples/website-literate/lake-manifest.json
- examples/website-literate/lakefile.toml
- examples/website-literate/lean-toolchain
- examples/website/DemoSiteMain.lean
- lake-manifest.json
- lean-toolchain
- src/verso-blog/VersoBlog.lean
- src/verso-blog/VersoBlog/LiterateLeanPage.lean
- src/verso-blog/VersoBlog/LiterateLeanPage/Options.lean
- src/verso-blog/VersoBlog/Site/Syntax.lean
- src/verso/Verso/Doc/Concrete.lean
- src/verso/Verso/Doc/Concrete/InlineString.lean
- src/verso/Verso/Doc/Name.lean
- src/verso/Verso/Parser.lean
This will be the basis of getting the examples onto the new website.
> feat: elaborating Verso pages from Lean with Markdown

- src/verso-blog/VersoBlog.lean
- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/Basic.lean
- src/verso-manual/VersoManual/Draft.lean
- src/verso-manual/VersoManual/InlineLean.lean
- src/verso-manual/VersoManual/InlineLean/Block.lean
- src/verso-manual/VersoManual/InlineLean/IO.lean
- src/verso-manual/VersoManual/InlineLean/IO/Context.lean
- src/verso-manual/VersoManual/InlineLean/LongLines.lean
- src/verso-manual/VersoManual/InlineLean/Option.lean
- src/verso-manual/VersoManual/InlineLean/Outputs.lean
- src/verso-manual/VersoManual/InlineLean/Scopes.lean
- src/verso-manual/VersoManual/InlineLean/Signature.lean
- src/verso-manual/VersoManual/InlineLean/SyntaxError.lean
- src/verso-manual/VersoManual/License.lean
- src/verso-manual/VersoManual/WithoutAsync.lean
- src/verso/Verso.lean
- src/verso/Verso/Doc/ArgParse.lean
- src/verso/Verso/EditDistance.lean
- src/verso/Verso/ExpectString.lean
- src/verso/Verso/SyntaxUtils.lean
Upstream the reference manual's Lean code handling tools. This makes it usable in other projects, and helps standardize its tools for handling scopes and variables.
> chore: upstream Lean code tooling from the language reference

- src/verso/Verso/Doc/Lsp.lean
This uses tasks and threads in a smarter way, and avoids tricky issues with `Task.get` panicking on sync threads.
> fix: better task management in Verso LSP

- examples/website-examples/lake-manifest.json
- examples/website-literate/lake-manifest.json
- lake-manifest.json
- src/verso/Verso/Doc/ArgParse.lean
- src/verso/Verso/Doc/Concrete.lean
- src/verso/Verso/Doc/Elab.lean
1. ArgParse can use monadic actions as fallbacks
2. Backtracking bug fixed in ArgParse
3. Macro expansion for Verso syntax elements
> feat: support for FP-Lean port

- .github/workflows/pull-request-toolchains.yml
- README.md
@kim-em I believe this matches our conversation
> chore: document and partially enforce new procedures

- examples/website-examples/lake-manifest.json
- examples/website-literate/lake-manifest.json
- examples/website/DemoSite/About.lean
- lake-manifest.json
- src/verso-blog/VersoBlog.lean
- src/verso-blog/VersoBlog/Basic.lean
- src/verso-blog/VersoBlog/Component.lean
- src/verso-blog/VersoBlog/Generate.lean
- src/verso-blog/VersoBlog/Site.lean
- src/verso-blog/VersoBlog/Template.lean
- src/verso-blog/VersoBlog/Traverse.lean
- src/verso-manual/VersoManual.lean
- src/verso-manual/VersoManual/LocalContents.lean
- src/verso/Verso/Doc.lean
- src/verso/Verso/Doc/Html.lean
- src/verso/Verso/Parser.lean
Components bundle together HTML, JS, and CSS.
> feat: components in blog genre

- README.md
This seems to have been copy-pasted from the previous paragraph ...
> README: fix example output path

- src/verso/Verso/Parser.lean
> fix: allow list item contents to be on new line

- src/verso/Verso/Output/Html.lean
Reopening the PR after rewriting the git history
> fix: behavior of SVG tags inside the HTML

- examples/anchor-examples/lake-manifest.json
- examples/documented-package/lake-manifest.json
- examples/website-examples/lake-manifest.json
- examples/website-literate/lake-manifest.json
- lake-manifest.json
- src/verso/Verso.lean
- src/verso/Verso/Linters.lean
> feat: linter for Unicode typography

- examples/textbook/DemoTextbookMain.lean
It seems that a relative path became absolute. Now it's relative again.
> fix: demo textbook would delete files

- examples/anchor-examples/lake-manifest.json
- examples/documented-package/lake-manifest.json
- examples/website-examples/lake-manifest.json
- examples/website-literate/lake-manifest.json
- lake-manifest.json
- src/verso-blog/VersoBlog/LiterateLeanPage.lean
- src/verso-manual/VersoManual/Docstring.lean
- src/verso/Verso/Code/External.lean
- src/verso/Verso/Code/Highlighted.lean
This PR allows Verso to build in light of the changes introduced in SubVerso by [#138](https://github.com/leanprover/subverso/pull/138).
> chore: update highlighting contexts to reflect SubVerso changes
